#!/usr/bin/env python3

# File: icons.py
# Author: Hadi Cahyadi <cumulus13@gmail.com>
# Date: 2026-07-01
# Description: 
# License: MIT


class Icons:
    """Unicode icons for different message types"""
    MESSAGE = "💭 "
    SUCCESS = "✅ "
    ERROR = "❌ "
    WARNING = "⚠️ "
    INFO = "ℹ️ "
    SETTING = "🔧 "
    GIT = "𖦥 "
    GITHUB = "🐙 "
    VERSION = "📦 "
    TAG = "🏷️ "
    PUSH = "🚀 "
    PULL = "⬇️ "
    CLONE = "📥 "
    COMMIT = "💾 "
    REMOTE = "🌐 "
    FOLDER = "📁 "
    FILE = "📄 "
    LOCK = "🔒 "
    UNLOCK = "🔓 "
    SEARCH = "🔍 "
    CLIPBOARD = "📋 "
    CONFIG = "⚙️ "
    TIME = "⏰ "
    NOTIFICATION = "🔔 "
    DOWNLOAD = "⬇️ "
    RELEASE = "🎯 "
    USERNAME = "🙎 "
    OWNER = "🚹 "
    NODE = "📮 "
    KEY = "🔑 "
    TOKEN = "🗝️ "
    DATE = "📅 "
    EMAIL = "📧 "
    LINK = "🔗 "
    MARK = "🔖 "
    FIND = "🔎 "
    BLOCK = "🧱 "
    GITIGNORE = "🌿 "
    DIFF = "⚓ "
    COLOR = "🎨 "
    LINENUMBER = "🥦 "
    PENDING = "📧 "
    CANCEL = "⛔ "
    CHAPTER = "🎬 "
    RUST = "🦀 "
    DOTNET = "C++ "
    GOLANG = "🇬🇴 "
    NSIS = "🧪 "
    TEST = "👌 "
    PYTHON = "🐍 "
    ANY = "🍀 "
    DOWNLOAD = "⬇️ "
    BUG = "🐞 "
    ASK = "❓ "
    FORWARD = "⏩ "
    STAR = "⭐ "
    TREE1 = "⛕ "
    TREE2 = "𖣂 "
    FORK = "🔱 "
    PAGINATION = "🔢 "
    LIGHTNING = "⚡ "
    CLOUD = "☁︎ "
    HOME = "🏠 "
    SERVER = "📡 "
    SHOW = "👀 "
    CHECK = "✓⃝ "
    DETAIL = "ⓘ "